### ISSUE TITLE
Crash when connecting to server on Windows

### ISSUE THREAD

**Issue by marcusball** [Thinkofname/steven-rust#34]
I get a crash immediately after connecting to a server. I'm able to successfully establish a connection, but it crashes while loading the world.

I'm using AppVeyor build 67, x64. 

Stack Trace:
```
thread '<main>' panicked at 'no entry found for key', ../src/libcore\option.rs:700
stack backtrace:
   0:     0x7ff74b52628b - std::rt::lang_start::h12d9b3310b48a726
   1:     0x7ff74b52568d - std::rt::lang_start::h12d9b3310b48a726
   2:     0x7ff74b51327f - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
   3:     0x7ff74b51419d - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196
   4:     0x7ff74b51ff2b - rust_begin_unwind
   5:     0x7ff74b52bdd5 - core::panicking::panic_fmt::ha6b3c19493c123b3
   6:     0x7ff74b5313a4 - core::option::expect_failed::h993b9b74ab42a489
   7:     0x7ff74b0213e1 - expect
                        at C:\projects\src\libcore\option.rs:294
   8:     0x7ff74b188794 - index
                        at C:\projects\src\libstd\collections\hash\map.rs:1219
   9:     0x7ff74b187cb9 - set_block
                        at C:\projects\steven-rust\src\world\mod.rs:985
  10:     0x7ff74b141d71 - set_block
                        at C:\projects\steven-rust\src\world\mod.rs:824
  11:     0x7ff74b13db2b - set_block_raw
                        at C:\projects\steven-rust\src\world\mod.rs:100
  12:     0x7ff74b15b294 - update_range
                        at C:\projects\steven-rust\src\world\mod.rs:141
  13:     0x7ff74b1397e7 - load_chunk
                        at C:\projects\steven-rust\src\world\mod.rs:666
  14:     0x7ff74b11e181 - on_chunk_data
                        at C:\projects\steven-rust\src\server\mod.rs:741
  15:     0x7ff74b11843f - entity_tick
                        at C:\projects\steven-rust\src\server\mod.rs:360
  16:     0x7ff74af00aa5 - tick
                        at C:\projects\steven-rust\src\server\mod.rs:323
  17:     0x7ff74aeccc2d - main
                        at C:\projects\steven-rust\src\main.rs:225
  18:     0x7ff74b525048 - std::rt::lang_start::h12d9b3310b48a726
  19:     0x7ff74b51fe98 - std::sys_common::unwind::inner_try::h4e97625a08807651
  20:     0x7ff74b524df7 - std::rt::lang_start::h12d9b3310b48a726
  21:     0x7ff74af06819 - main
  22:     0x7ff74b55fcdf - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264
  23:     0x7ff85e3f8101 - BaseThreadInitThunk
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
```

PS: Looks game looks great! Awesome work!

**Comment by Thinkofname** [comment]
I haven't been able to cause it consistently, have you got a server that it happens all the time on?

**Comment by Thinkofname** [comment]
Strike that, seems to happen on mineplex all the time. Looking into it

**Comment by marcusball** [comment]
I only just downloaded this, so I don't have a long sample period, but it's happened every time I tried to connect to this server. Unfortunately, it's a closed server of which I am not an admin, so I can't point you toward it. 

It's running CraftBukkit 1.9.2.

I'm currently trying to find a public server running the same version to see if it's a server version issue.

**Comment by Thinkofname** [comment]
Apparently not completely fixed
